import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations
const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navigation
    'nav.dashboard': 'Tableau de Bord',
    'nav.overview': 'Vue d\'ensemble',
    'nav.properties': 'Propriétés',
    'nav.tenants': 'Locataires',
    'nav.payments': 'Paiements',
    'nav.expenses': 'Analyse des Dépenses',
    'nav.expenseAnalysis': 'Analyse Détaillée',
    'nav.admin': 'Gestion Admin',
    'nav.settings': 'Paramètres',
    'nav.notifications': 'Notifications',
    
    // Dashboard Overview
    'dashboard.totalProperties': 'Propriétés Totales',
    'dashboard.activeTenants': 'Locataires Actifs',
    'dashboard.monthlyRevenue': 'Revenus Mensuels',
    'dashboard.pendingBills': 'Factures en Attente',
    'dashboard.fromDatabase': 'Depuis la base de données',
    'dashboard.currentlyActive': 'Actuellement actifs',
    'dashboard.thisMonth': 'Ce mois-ci',
    'dashboard.awaitingPayment': 'En attente de paiement',
    'dashboard.revenueOverview': 'Aperçu des Revenus',
    'dashboard.propertyPerformance': 'Performance des Propriétés',
    'dashboard.recentActivity': 'Activité Récente',
    'dashboard.quickActions': 'Actions Rapides',
    'dashboard.exportData': 'Exporter les Données',
    'dashboard.exportAllData': 'Exporter toutes les données',
    
    // Settings
    'settings.title': 'Paramètres',
    'settings.account.title': 'Paramètres du Compte',
    'settings.account.description': 'Gérez vos préférences et paramètres de compte.',
    'settings.language.title': 'Préférences de Langue',
    'settings.language.description': 'Choisissez votre langue préférée pour l\'interface.',
    'settings.language.label': 'Langue',
    'settings.language.french': 'Français',
    'settings.language.english': 'Anglais',
    'settings.profile.name': 'Nom du Profil',
    'settings.profile.name.placeholder': 'Entrez votre nom de profil',
    'settings.profile.email': 'Email',
    'settings.profile.email.placeholder': 'Entrez votre email',
    'settings.signature.title': 'Signature du bailleur',
    'settings.signature.description': 'Téléchargez une image de votre signature pour l\'ajouter automatiquement aux quittances PDF.',
    'settings.signature.upload': 'Télécharger la signature',
    'settings.signature.change': 'Changer la signature',
    'settings.signature.remove': 'Supprimer la signature',
    'settings.signature.current': 'Signature actuelle',
    'settings.signature.none': 'Aucune signature enregistrée',
    'settings.save': 'Enregistrer les Modifications',
    'settings.saving': 'Enregistrement...',
    'settings.saved': 'Enregistré',
    'settings.password.title': 'Changer le Mot de Passe',
    'settings.password.description': 'Mettez à jour votre mot de passe pour sécuriser votre compte.',
    'settings.password.change': 'Changer le Mot de Passe',
    'settings.password.current': 'Mot de Passe Actuel',
    'settings.password.current.placeholder': 'Entrez votre mot de passe actuel',
    'settings.password.new': 'Nouveau Mot de Passe',
    'settings.password.new.placeholder': 'Entrez votre nouveau mot de passe (min. 6 caractères)',
    'settings.password.confirm': 'Confirmer le Nouveau Mot de Passe',
    'settings.password.confirm.placeholder': 'Confirmez votre nouveau mot de passe',
    'settings.password.changing': 'Changement...',
    'settings.password.success': '✅ Mot de passe changé avec succès! Vous pouvez maintenant vous connecter avec votre nouveau mot de passe.',
    'settings.password.current.required': 'Le mot de passe actuel est requis',
    'settings.password.new.required': 'Le nouveau mot de passe est requis',
    'settings.password.new.min': 'Le nouveau mot de passe doit contenir au moins 6 caractères',
    'settings.password.mismatch': 'Les mots de passe ne correspondent pas',
    'settings.password.failed': 'Échec du changement de mot de passe',
    'settings.logout.title': 'Déconnexion',
    'settings.logout.description': 'Déconnectez-vous de votre compte.',
    'settings.logout.button': 'Se déconnecter',
    'settings.cancel': 'Annuler',
    
    // Payments Management
    'payments.title': 'Gestion des Paiements',
    'payments.totalBills': 'Total des Factures',
    'payments.totalAmount': 'Montant Total',
    'payments.pending': 'En Attente',
    'payments.overdue': 'En Retard',
    'payments.create': 'Créer une Facture',
    'payments.filter': 'Filtrer',
    'payments.search': 'Rechercher...',
    'payments.status.all': 'Tous les Statuts',
    'payments.status.pending': 'En Attente',
    'payments.status.paid': 'Payé',
    'payments.status.overdue': 'En Retard',
    'payments.status.receipt_sent': 'Reçu Envoyé',
    'payments.table.select': 'Sélectionner',
    'payments.table.tenant': 'Locataire',
    'payments.table.property': 'Propriété',
    'payments.table.amount': 'Montant',
    'payments.table.month': 'Mois',
    'payments.table.status': 'Statut',
    'payments.table.actions': 'Actions',
    'payments.table.view': 'Voir',
    'payments.table.download': 'Télécharger',
    'payments.table.delete': 'Supprimer',
    'payments.table.markPaid': 'Marquer comme Payé',
    'payments.table.undoPayment': 'Annuler le Paiement',
    'payments.create.title': 'Créer une Nouvelle Facture',
    'payments.create.tenant': 'Locataire',
    'payments.create.property': 'Propriété',
    'payments.create.amount': 'Montant',
    'payments.create.charges': 'Charges',
    'payments.create.month': 'Mois',
    'payments.create.paymentDate': 'Date de Paiement',
    'payments.create.description': 'Description',
    'payments.create.submit': 'Créer la Facture',
    'payments.create.cancel': 'Annuler',
    'payments.preview.title': 'Aperçu de la Facture',
    'payments.preview.landlord': 'Bailleur',
    'payments.preview.tenant': 'Locataire',
    'payments.preview.property': 'Détails du Bien',
    'payments.preview.rent': 'Loyer',
    'payments.preview.charges': 'Charges',
    'payments.preview.total': 'Total',
    'payments.preview.paymentDate': 'Date du Paiement',
    'payments.preview.month': 'Mois',
    'payments.preview.status': 'Statut',
    'payments.preview.description': 'Description',
    'payments.preview.close': 'Fermer',
    'payments.preview.download': 'Télécharger le PDF',
    'payments.noBills': 'Aucune facture trouvée',
    'payments.loading': 'Chargement...',
    'payments.error': 'Erreur lors du chargement des factures',
    'payments.tenant': 'Locataire',
    'payments.property': 'Propriété',
    'payments.nonRenseigne': 'Non renseigné',
    'payments.nA': 'N/A',
    
    // Tenants Management
    'tenants.title': 'Gestion des Locataires',
    'tenants.add': 'Ajouter un Locataire',
    'tenants.edit': 'Modifier le Locataire',
    'tenants.name': 'Nom',
    'tenants.email': 'Email',
    'tenants.phone': 'Téléphone',
    'tenants.property': 'Propriété',
    'tenants.status': 'Statut',
    'tenants.status.active': 'Actif',
    'tenants.status.inactive': 'Inactif',
    'tenants.status.expired': 'Expiré',
    'tenants.checkIn': 'Date d\'Entrée',
    'tenants.checkOut': 'Date de Sortie',
    'tenants.save': 'Enregistrer',
    'tenants.cancel': 'Annuler',
    'tenants.delete': 'Supprimer',
    'tenants.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer ce locataire?',
    'tenants.noTenants': 'Aucun locataire trouvé',
    'tenants.loading': 'Chargement...',
    
    // Properties Management
    'properties.title': 'Gestion des Propriétés',
    'properties.add': 'Ajouter une Propriété',
    'properties.edit': 'Modifier la Propriété',
    'properties.titleField': 'Titre',
    'properties.address': 'Adresse',
    'properties.city': 'Ville',
    'properties.postalCode': 'Code Postal',
    'properties.country': 'Pays',
    'properties.rent': 'Loyer Mensuel',
    'properties.type': 'Type de Propriété',
    'properties.save': 'Enregistrer',
    'properties.cancel': 'Annuler',
    'properties.delete': 'Supprimer',
    'properties.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer cette propriété?',
    'properties.noProperties': 'Aucune propriété trouvée',
    'properties.loading': 'Chargement...',
    'properties.photo': 'Photo',
    'properties.uploadPhoto': 'Télécharger une Photo',
    
    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.close': 'Fermer',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.confirm': 'Confirmer',
    'common.search': 'Rechercher...',
    'common.filter': 'Filtrer',
    'common.actions': 'Actions',
    'common.status': 'Statut',
    'common.date': 'Date',
    'common.amount': 'Montant',
    'common.description': 'Description',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.overview': 'Overview',
    'nav.properties': 'Properties',
    'nav.tenants': 'Tenants',
    'nav.payments': 'Payments',
    'nav.expenses': 'Expense Analytics',
    'nav.expenseAnalysis': 'Detailed Analysis',
    'nav.admin': 'Admin Management',
    'nav.settings': 'Settings',
    'nav.notifications': 'Notifications',
    
    // Dashboard Overview
    'dashboard.totalProperties': 'Total Properties',
    'dashboard.activeTenants': 'Active Tenants',
    'dashboard.monthlyRevenue': 'Monthly Revenue',
    'dashboard.pendingBills': 'Pending Bills',
    'dashboard.fromDatabase': 'From database',
    'dashboard.currentlyActive': 'Currently active',
    'dashboard.thisMonth': 'This month',
    'dashboard.awaitingPayment': 'Awaiting payment',
    'dashboard.revenueOverview': 'Revenue Overview',
    'dashboard.propertyPerformance': 'Property Performance',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.exportData': 'Export Data',
    'dashboard.exportAllData': 'Export all data',
    
    // Settings
    'settings.title': 'Settings',
    'settings.account.title': 'Account Settings',
    'settings.account.description': 'Manage your account preferences and settings.',
    'settings.language.title': 'Language Preferences',
    'settings.language.description': 'Choose your preferred language for the interface.',
    'settings.language.label': 'Language',
    'settings.language.french': 'French',
    'settings.language.english': 'English',
    'settings.profile.name': 'Profile Name',
    'settings.profile.name.placeholder': 'Enter your profile name',
    'settings.profile.email': 'Email',
    'settings.profile.email.placeholder': 'Enter your email',
    'settings.signature.title': 'Landlord Signature',
    'settings.signature.description': 'Upload an image of your signature to automatically display it on PDF receipts.',
    'settings.signature.upload': 'Upload signature',
    'settings.signature.change': 'Change signature',
    'settings.signature.remove': 'Remove signature',
    'settings.signature.current': 'Current signature',
    'settings.signature.none': 'No signature saved',
    'settings.save': 'Save Changes',
    'settings.saving': 'Saving...',
    'settings.saved': 'Saved',
    'settings.password.title': 'Change Password',
    'settings.password.description': 'Update your password to secure your account.',
    'settings.password.change': 'Change Password',
    'settings.password.current': 'Current Password',
    'settings.password.current.placeholder': 'Enter your current password',
    'settings.password.new': 'New Password',
    'settings.password.new.placeholder': 'Enter your new password (min. 6 characters)',
    'settings.password.confirm': 'Confirm New Password',
    'settings.password.confirm.placeholder': 'Confirm your new password',
    'settings.password.changing': 'Changing...',
    'settings.password.success': '✅ Password changed successfully! You can now log in with your new password.',
    'settings.password.current.required': 'Current password is required',
    'settings.password.new.required': 'New password is required',
    'settings.password.new.min': 'New password must contain at least 6 characters',
    'settings.password.mismatch': 'Passwords do not match',
    'settings.password.failed': 'Password change failed',
    'settings.logout.title': 'Logout',
    'settings.logout.description': 'Log out of your account.',
    'settings.logout.button': 'Logout',
    'settings.cancel': 'Cancel',
    
    // Payments Management
    'payments.title': 'Payments Management',
    'payments.totalBills': 'Total Bills',
    'payments.totalAmount': 'Total Amount',
    'payments.pending': 'Pending',
    'payments.overdue': 'Overdue',
    'payments.create': 'Create Bill',
    'payments.filter': 'Filter',
    'payments.search': 'Search...',
    'payments.status.all': 'All Statuses',
    'payments.status.pending': 'Pending',
    'payments.status.paid': 'Paid',
    'payments.status.overdue': 'Overdue',
    'payments.status.receipt_sent': 'Receipt Sent',
    'payments.table.select': 'Select',
    'payments.table.tenant': 'Tenant',
    'payments.table.property': 'Property',
    'payments.table.amount': 'Amount',
    'payments.table.month': 'Month',
    'payments.table.status': 'Status',
    'payments.table.actions': 'Actions',
    'payments.table.view': 'View',
    'payments.table.download': 'Download',
    'payments.table.delete': 'Delete',
    'payments.table.markPaid': 'Mark as Paid',
    'payments.table.undoPayment': 'Undo Payment',
    'payments.create.title': 'Create New Bill',
    'payments.create.tenant': 'Tenant',
    'payments.create.property': 'Property',
    'payments.create.amount': 'Amount',
    'payments.create.charges': 'Charges',
    'payments.create.month': 'Month',
    'payments.create.paymentDate': 'Payment Date',
    'payments.create.description': 'Description',
    'payments.create.submit': 'Create Bill',
    'payments.create.cancel': 'Cancel',
    'payments.preview.title': 'Bill Preview',
    'payments.preview.landlord': 'Landlord',
    'payments.preview.tenant': 'Tenant',
    'payments.preview.property': 'Property Details',
    'payments.preview.rent': 'Rent',
    'payments.preview.charges': 'Charges',
    'payments.preview.total': 'Total',
    'payments.preview.paymentDate': 'Payment Date',
    'payments.preview.month': 'Month',
    'payments.preview.status': 'Status',
    'payments.preview.description': 'Description',
    'payments.preview.close': 'Close',
    'payments.preview.download': 'Download PDF',
    'payments.noBills': 'No bills found',
    'payments.loading': 'Loading...',
    'payments.error': 'Error loading bills',
    'payments.tenant': 'Tenant',
    'payments.property': 'Property',
    'payments.nonRenseigne': 'Not specified',
    'payments.nA': 'N/A',
    
    // Tenants Management
    'tenants.title': 'Tenants Management',
    'tenants.add': 'Add Tenant',
    'tenants.edit': 'Edit Tenant',
    'tenants.name': 'Name',
    'tenants.email': 'Email',
    'tenants.phone': 'Phone',
    'tenants.property': 'Property',
    'tenants.status': 'Status',
    'tenants.status.active': 'Active',
    'tenants.status.inactive': 'Inactive',
    'tenants.status.expired': 'Expired',
    'tenants.checkIn': 'Check-in Date',
    'tenants.checkOut': 'Check-out Date',
    'tenants.save': 'Save',
    'tenants.cancel': 'Cancel',
    'tenants.delete': 'Delete',
    'tenants.deleteConfirm': 'Are you sure you want to delete this tenant?',
    'tenants.noTenants': 'No tenants found',
    'tenants.loading': 'Loading...',
    
    // Properties Management
    'properties.title': 'Properties Management',
    'properties.add': 'Add Property',
    'properties.edit': 'Edit Property',
    'properties.titleField': 'Title',
    'properties.address': 'Address',
    'properties.city': 'City',
    'properties.postalCode': 'Postal Code',
    'properties.country': 'Country',
    'properties.rent': 'Monthly Rent',
    'properties.type': 'Property Type',
    'properties.save': 'Save',
    'properties.cancel': 'Cancel',
    'properties.delete': 'Delete',
    'properties.deleteConfirm': 'Are you sure you want to delete this property?',
    'properties.noProperties': 'No properties found',
    'properties.loading': 'Loading...',
    'properties.photo': 'Photo',
    'properties.uploadPhoto': 'Upload Photo',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.confirm': 'Confirm',
    'common.search': 'Search...',
    'common.filter': 'Filter',
    'common.actions': 'Actions',
    'common.status': 'Status',
    'common.date': 'Date',
    'common.amount': 'Amount',
    'common.description': 'Description',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    // Load from localStorage or default to French
    const saved = localStorage.getItem('app_language') as Language;
    return saved && (saved === 'fr' || saved === 'en') ? saved : 'fr';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
    // Update document language attribute
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    // Set initial language on mount
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

